using System.Collections.Generic;

namespace Hangman.Models
{
  public class Guess 
  {
    public string Letter { get; set; }
    public bool InWord { get; set; }
    public int Id {get;}
    private static List<Guess> _instances = new List<Guess>();
    // public string Art {get;set;}
    // id? - restful conventions - find, /parent{id} generated by a static list var of Guesses 

    public Guess(string letter)
    {
      Letter = letter;
      _instances.Add(this); //if it's not static, we need the instance
      Id = _instances.Count;
      // InWord = WordFunction();
      //leave it off at first, or call the parent's function here
    }

    //find
  }
}